language: java
install: true
matrix:
  include:
  - jdk: oraclejdk8
script:
- javac -d . src/*.java
- jar cfe cg-c4l.jar Referee *.class
deploy:
  provider: releases
  api_key:
    secure: 4XYHeKkc6uEvYDUOeoqRzJbAuD17oKuGrBjCk4HB0saj4/PSmAraBAVmAIH70Rh+FlLwAitnUIREeK3Z44/0AZXV/RpU5w/VtC+9avKlaqWmRq3FU813wNSDjp44AZDeo6BWU4PiIDdhhxEQpzfHj6NdJXWSMN6ItnyedTQgNt8S4UG+3fXw0rM5w0JMAI9D0Z4QSp9B++UmE0/NNgA4+28mVsLMgdqn0b/A8cEpLUl9It1AZYU5zxMIywjAB4HA1Z1zyZVpeGa3Es2JGdOBWIiCLaa8sjV/6uTZTzD5OE4C6pf92gQT1xeG5LzvLNt1qEg40uCUVuMUVgB2wP6L/A96wPxmRiVobwDdfGf4ujmenOEuRFZXE5e37XbDp1bo8xzlo0xUBLMK13VSr7MpxCv0ATdMWIgblPsJkSwuUvK+1Ue3/bkf7Zmic6/VcUdaHkR0+KJBldf9KI5oSLamREAmc2ynxWYFD2uCGD93kMxRchjwQA+YnLdlUDpMAAbOHDWpR1oegVIZ0zbKed81urPm3sBJzwoUffl/8FrY+B+HNjjEUQVUxkEs64lcemsEYZwFNgXdcBR3I8OVh4u63Koi6ATP8Xb1rYPrvge6bZn+gshtxyRXoFBrr9HWG5D7I1Hj/+UBBL4Rr1CNphpE+S+n4I52TQvAYKBZWk46NsM=
  file: cg-c4l.jar
  on:
    tags: true
